apiVersion: v1
kind: PersistentVolume
metadata:
  name: notes-pv
  labels:
    app: notes-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  gcePersistentDisk:
    pdName: notes-disk
    fsType: ext4