apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
  namespace: default
  labels:
    app: notes-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo