apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
  namespace: default
  labels:
    app: notes-app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi                     # 1 GB disk talep et
